# Conda environment matching the actual test environment
# Based on requirements files showing sklearn 1.4.1.post1 was used
# Mac ARM64 (M1/M2/M3) compatible

name: spec2class_legacy
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Python version  
  - python=3.12
  
  # Core scientific packages - matching requirements files
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.12.0
  
  # PyTorch for Mac ARM64 (no separate CPU-only build)
  - pytorch=2.2.1
  
  # Other dependencies
  - pip
  - pip:
      - scikit-learn==1.4.1.post1
      - huggingface_hub>=0.23
      - tqdm
      - pytest>=7.0
      - pytest-cov>=4.0
      - joblib==1.3.2
      - threadpoolctl==3.3.0